services:
  damn-redis:
    image: redis:latest
    container_name: damn-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - damn-network

  damn-mongodb:
    image: mongo:6.0
    container_name: damn-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - damn-network

  damn-postgres:
    image: postgres:latest
    container_name: damn_postgres
    restart: always
    environment:
      - POSTGRES_USER=damn
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=damn_maps
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - damn-network

  damn-neo4j:
    image: neo4j:5.26.5
    container_name: damn-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/yourpassword
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_server_memory_heap_initial__size=1g
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=1g
    volumes:
      - ./apoc-5.26.5-core.jar:/var/lib/neo4j/plugins/apoc-5.26.5-core.jar
      - neo4j-data:/data
      - neo4j-logs:/logs
    deploy:
      resources:
        limits:
          memory: 6g
    networks:
      - damn-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7474" ]
      interval: 10s
      timeout: 5s
      retries: 5

  damn-api-gateway:
    build: ./damn-api-gateway
    container_name: damn-api-gateway
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./application.properties:/app/application.properties
    networks:
      - damn-network

  damn-data-manager:
    build: ./damn-data-manager
    container_name: damn-data-manager
    restart: always
    ports:
      - "8084:8084"
    volumes:
      - ./application.properties:/app/application.properties
    depends_on:
      - damn-mongodb
    networks:
      - damn-network

  damn-map-service:
    build: ./damn-map-service
    container_name: damn-map-service
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./application.properties:/app/application.properties
    networks:
      - damn-network

  damn-route-manager:
    build: ./damn-route-manager
    container_name: damn-route-manager
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./application.properties:/app/application.properties
    environment:
      - SPRING_REDIS_HOST=damn-redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - damn-redis
    networks:
      - damn-network

  damn-route-provider:
    build: ./damn-route-provider
    container_name: damn-route-provider
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./application.properties:/app/application.properties
    networks:
      - damn-network

  damn-route-scorer:
    build: ./damn-route-scorer
    container_name: damn-route-scorer
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - ./application.properties:/app/application.properties
    networks:
      - damn-network

networks:
  damn-network:
    driver: bridge

volumes:
  redis-data:
  mongo-data:
  postgres-data:
  neo4j-data:
  neo4j-logs: